{
    "openapi": "3.0.3",
    "info": {
        "title": "TodoList RESTful API",
        "version": "1",
        "description": "OpenAPI for Todolist RESTful API",
        "termsOfService": "https://www.programmerzamannow.com",
        "contact": {
            "name": "Arman Dwi Pangestu",
            "email": "armandwi.pangestu7@gmail.com",
            "url": "https://armandwipangestu.vercel.app"
        },
        "license": {
            "name": "APACHE 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "servers": [
        {
            "description": "Todolist RESTful API Server",
            "url": "https://{environment}.programmerzamannow.com/api/v1",
            "variables": {
                "environment": {
                    "description": "Server Environment",
                    "default": "dev",
                    "enum": ["dev", "qa", "prod"]
                }
            }
        }
    ],
    "externalDocs": {
        "description": "Youtube Programmer Zaman Now",
        "url": "https://www.youtube.com/c/ProgrammerZamanNow"
    },
    "tags": [
        {
            "name": "todolist",
            "description": "Everything about todolist"
        }
    ],
    "paths": {
        "/todolist": {
            "get": {
                "tags": ["todolist"],
                "summary": "Get All TodoList",
                "description": "Get all active todolist by default",
                "parameters": [
                    {
                        "name": "include_done",
                        "in": "query",
                        "description": "Include done todolist in the result",
                        "required": false,
                        "schema": {
                            "type": "boolean",
                            "nullable": true,
                            "default": false
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "description": "Filter todolist by name",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "examples": {
                            "java": {
                                "description": "Example name Java",
                                "value": "Java"
                            },
                            "php": {
                                "description": "Example name PHP",
                                "value": "PHP"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success get all todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ArrayTodolist"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Exdample success get all todolist",
                                        "value": [
                                            {
                                                "id": "1",
                                                "name": "Java",
                                                "priority": 3,
                                                "tags": ["Java", "Programming"]
                                            },
                                            {
                                                "id": "2",
                                                "name": "PHP",
                                                "priority": 5,
                                                "tags": ["PHP", "Programming"]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["todolist"],
                "summary": "Create new Todolist",
                "description": "Create new Todolist to database",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples": {
                                "java": {
                                    "description": "Example create todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": ["Java", "Programming"]
                                    }
                                },
                                "php": {
                                    "description": "Example create todolist PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 5,
                                        "tags": ["PHP", "Programming"]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success create todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success create Java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags": ["Java", "Programming"]
                                        }
                                    },
                                    "php": {
                                        "description": "Success create PHP todolist",
                                        "value": {
                                            "id": "2",
                                            "name": "PHP",
                                            "priority": 5,
                                            "tags": ["PHP", "Programming"]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/todolist/{todolistId}": {
            "put": {
                "tags": ["todolist"],
                "summary": "Update exisiting todolist",
                "description": "Update existing todolist in database",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/TodolistId"
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples": {
                                "java": {
                                    "description": "Example create todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": ["Java", "Programming"]
                                    }
                                },
                                "php": {
                                    "description": "Example create todolist PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 5,
                                        "tags": ["PHP", "Programming"]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success update todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success create Java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags": ["Java", "Programming"]
                                        }
                                    },
                                    "php": {
                                        "description": "Success create PHP todolist",
                                        "value": {
                                            "id": "2",
                                            "name": "PHP",
                                            "priority": 5,
                                            "tags": ["PHP", "Programming"]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": ["todolist"],
                "summary": "Delete existing todolist",
                "description": "Delete existing todolist in database",
                "parameters": [
                    {
                        "$ref": "#/components/parameters/TodolistId"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success delete todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Success delete todolist",
                                        "value": {
                                            "success": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Failed delete not found todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "failed": {
                                        "description": "Failed delete todolist",
                                        "value": {
                                            "success": false
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "parameters": {
            "TodolistId": {
                "name": "todolistId",
                "in": "path",
                "description": "Todolist id for updated",
                "required": true,
                "schema": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 100
                },
                "examples": {
                    "java": {
                        "description": "Sample todolist id for Java",
                        "value": "1"
                    },
                    "php": {
                        "description": "Sample todolist id for PHP",
                        "value": "2"
                    }
                }
            }
        },
        "schemas": {
            "Todolist": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "priority": {
                        "type": "number",
                        "format": "int32"
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "CreateOrUpdateTodolist": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "minimum": 1,
                        "required": true
                    },
                    "priority": {
                        "type": "integer",
                        "format": "int32",
                        "default": 1,
                        "required": true
                    },
                    "tags": {
                        "type": "array",
                        "required": false,
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "minLength": 1
                        }
                    }
                }
            },
            "ArrayTodolist": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Todolist"
                }
            }
        }
    }
}
